### ISSUE TITLE
Pre-assembly on lyberservices-test fails

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/pre-assembly#16]
Error message and trace below.

```
[lyberadmin@sul-lyberservices-test current]$ ROBOT_ENVIRONMENT=test bin/pre-assemble /dor/content/Rumsey23/atlas_test.yaml
2016-02-29 17:50:21 -0800: Pre-assembly started for combin8or
2016-02-29 17:50:21 -0800: 11 objects to pre-assemble
2016-02-29 17:50:21 -0800: 11 total objects found, 11 not yet complete, 0 already completed objects skipped
2016-02-29 17:50:21 -0800: 11 remaining in run | 11 running | 11 total incomplete | ~ remaining:
Working on '/dor/content/Rumsey23/0091/0091008.jp2' containing 1 files
/home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/digital_object.rb:580:in `initialize_assembly_workflow': initialize_assembly_workflow failed after 3 attempts; with URL of [URL sent to John separately]  (RuntimeError)
exception: 500 Internal Server Error
backtrace: ["/home/lyberadmin/pre-assembly/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'", "/home/lyberadmin/pre-assembly/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'", "/home/lyberadmin/pre-assembly/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'", "/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:853:in `start'", "/home/lyberadmin/pre-assembly/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'", "/home/lyberadmin/pre-assembly/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'", "/home/lyberadmin/pre-assembly/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'", "/home/lyberadmin/pre-assembly/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'", "/home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/digital_object.rb:565:in `initialize_assembly_workflow'", "/home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/digital_object.rb:144:in `pre_assemble'", "/home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:712:in `block in process_digital_objects'", "/home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:694:in `each'", "/home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:694:in `process_digital_objects'", "/home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:319:in `run_pre_assembly'", "bin/pre-assemble:35:in `<main>'"]
    from /home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/digital_object.rb:144:in `pre_assemble'
    from /home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:712:in `block in process_digital_objects'
    from /home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:694:in `each'
    from /home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:694:in `process_digital_objects'
    from /home/lyberadmin/pre-assembly/releases/20160225082109/lib/pre_assembly/bundle.rb:319:in `run_pre_assembly'
    from bin/pre-assemble:35:in `<main>'
```

**Comment by cbeer** [comment]
Can you send me the URL? It seems like it's a problem in dor-services-app, right?

**Comment by cbeer** [comment]
Looks like it's cause by a solr error. Maybe this environment hasn't been fully configured with the new index? @jmartin-sul ?

```
ERROR [2016-02-29 17:50:32] (8407)  :: #<RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request; Error: {'responseHeader'=>{'status'=>400,'QTime'=>1,'params'=>{'q'=>'objectType_ssim:"workflow" workflow_name_ssim:"assemblyWF"','start'=>'0','wt'=>'ruby'}},'error'=>{'msg'=>'undefined field objectType_ssim','code'=>400}}; ; URI: https://sul-solr.stanford.edu/solr/argo_test/select?wt=ruby&q=objectType_ssim%3A%22workflow%22+workflow_name_ssim%3A%22assemblyWF%22&start=0; ; Backtrace: /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-ext-1.0.3/lib/rsolr-ext/client.rb:21:in `find'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/services/search_service.rb:51:in `query'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor-services.rb:44:in `find_all'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/workflow_object.rb:14:in `find_by_name'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/workflow_object.rb:65:in `find_and_cache_workflow_xml_and_repo'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/workflow_object.rb:34:in `initial_repo'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/processable.rb:217:in `create_workflow'; /home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/processable.rb:223:in `initialize_workflow'>
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/rsolr-ext-1.0.3/lib/rsolr-ext/client.rb:21:in `find'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/services/search_service.rb:51:in `query'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor-services.rb:44:in `find_all'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/workflow_object.rb:14:in `find_by_name'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/workflow_object.rb:65:in `find_and_cache_workflow_xml_and_repo'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/workflow_object.rb:34:in `initial_repo'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/processable.rb:217:in `create_workflow'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/processable.rb:223:in `initialize_workflow'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.4.1/lib/dor/models/governable.rb:13:in `initiate_apo_workflow'
/home/lyberadmin/dor-services-app/releases/20160227011959/lib/dor_services_app.rb:189:in `block (4 levels) in <class:DorServicesApi>'

```

**Comment by jmartin-sul** [comment]
that does look like the sort of error you'd get from pointing to a solr collection with the old schema.  but `config/environments/test.rb` is pointing to the right place, as far as i can tell.  not sure what else there is to configure.  @peetucket?  @atz?

`grep -r solr .` in the current pre-assmbly deploy dir doesn't turn up any unexpected points of configuration.

**Comment by jmartin-sul** [comment]
ah, ok, sorry:  if @cbeer is saying it's a problem in dor-services-app config, that's plausible, and i've never dealt with that code or its deployment/configuration.  but dor-services-app-test should point to the `argo_stage` solr collection, if it doesn't already.

**Comment by cbeer** [comment]
`argo_stage`, you say? Looks like it's currently using the `argo_test` collection.

**Comment by jmartin-sul** [comment]
yup, that'd explain it.  `argo_test` is the old (argo 2.x) solr collection.  `argo_stage` is the new argo 3.x collection (though it is also an index of `dor-test`, somewhat confusingly).

**Comment by blalbrit** [comment]
Hi @jmartin-sul and @tingulfsen - @cbeer  suggests that one of you could make the config changes necessary to get pre-assembly and dor-services-app wired up properly on -stage. Who would be the best person to talk to about getting this into a testable state?

**Comment by jmartin-sul** [comment]
i believe the current plan is that @tingulfsen will get dor-services-app on lyberservices-test this afternoon, and dor-services-app on lyberservices-prod tomorrow.  i did pre-assembly on lyberservices-test already, and i'll get pre-assembly on lyberservices-prod tomorrow.
https://github.com/sul-dlss/argo/issues/490#issuecomment-189556788
