### ISSUE TITLE
Undefined Method: INITIALIZE_ASSEMBLY_WORKFLOW FAILED (Legacy Branch)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/pre-assembly#473]
[lyberadmin@sul-lyberservices-prod current]$ ROBOT_ENVIRONMENT=production bin/pre-assemble /dor/staging/GBTEST/gb_test.yaml
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=3.3.1 framework=ruby level=1 pid=7981
2019-04-16 17:14:04 -0700: Pre-assembly started for GB Test
2019-04-16 17:14:05 -0700: 5 objects to pre-assemble
2019-04-16 17:14:05 -0700: 5 total objects found, 5 not yet complete, 0 already completed objects skipped
2019-04-16 17:14:05 -0700: 5 remaining in run | 5 running | 5 total incomplete | ~ remaining:
Working on '/dor/staging/GBTEST/content/cs204mj1611' containing 130 files
** [Honeybadger] Reporting error id=b909bf36-a8c7-4b31-8249-785ba805ee1a level=1 pid=7981
** [Honeybadger] Reporting error id=9ab4bf82-ecb3-40e9-b739-1b0fa425b5af level=1 pid=7981
** [Honeybadger] Success ⚡ https://app.honeybadger.io/notice/b909bf36-a8c7-4b31-8249-785ba805ee1a id=b909bf36-a8c7-4b31-8249-785ba805ee1a code=201 level=1 pid=7981
** [Honeybadger] Success ⚡ https://app.honeybadger.io/notice/9ab4bf82-ecb3-40e9-b739-1b0fa425b5af id=9ab4bf82-ecb3-40e9-b739-1b0fa425b5af code=201 level=1 pid=7981
Traceback (most recent call last):
	9: from bin/pre-assemble:35:in `<main>'
	8: from /home/lyberadmin/pre-assembly/releases/20190416225811/lib/pre_assembly/bundle.rb:320:in `run_pre_assembly'
	7: from /home/lyberadmin/pre-assembly/releases/20190416225811/lib/pre_assembly/bundle.rb:694:in `process_digital_objects'
	6: from /home/lyberadmin/pre-assembly/releases/20190416225811/lib/pre_assembly/bundle.rb:694:in `each'
	5: from /home/lyberadmin/pre-assembly/releases/20190416225811/lib/pre_assembly/bundle.rb:712:in `block in process_digital_objects'
	4: from /home/lyberadmin/pre-assembly/releases/20190416225811/lib/pre_assembly/digital_object.rb:146:in `pre_assemble'
	3: from /home/lyberadmin/pre-assembly/releases/20190416225811/lib/pre_assembly/digital_object.rb:499:in `initialize_assembly_workflow'
	2: from /home/lyberadmin/pre-assembly/shared/bundle/ruby/2.5.0/gems/retries-0.0.5/lib/retries.rb:44:in `with_retries'
	1: from /home/lyberadmin/pre-assembly/shared/bundle/ruby/2.5.0/gems/retries-0.0.5/lib/retries.rb:49:in `rescue in with_retries'
/home/lyberadmin/pre-assembly/releases/20190416225811/lib/pre_assembly.rb:38:in `block in retry_handler': undefined method `      ** INITIALIZE_ASSEMBLY_WORKFLOW FAILED **; with params of {}; and trying attempt 1 of 5; delayed  seconds' for #<Method: PreAssembly::DigitalObject(PreAssembly::Logging)#log> (NoMethodError)

**Comment by blalbrit** [comment]
See: https://app.honeybadger.io/projects/52900/faults/39363284
