### ISSUE TITLE
fix flappy specs:  spec/features/preassembly_run/media_xx_spec.rb

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#977]
These specs often fail for me locally; I have never seen them fail in circleci.

I have tried to fiddle with cleanup/setup to avoid extra files in the tmp directory, but didn't find the magic yet.  If you don't see this, try running that spec file a few times in a row.

```
Failures:

  1) Create Media Audio object is expected to eq 12
     Failure/Error: expect(Dir.children(File.join(object_staging_dir, 'content')).size).to eq 12
     
       expected: 12
            got: 40
     
       (compared using ==)
     # ./spec/features/preassembly_run/media_audio_spec.rb:94:in `block (2 levels) in <top (required)>'
     # ./spec/features/preassembly_run/media_audio_spec.rb:65:in `block (3 levels) in <top (required)>'
     # ./spec/features/preassembly_run/media_audio_spec.rb:64:in `block (2 levels) in <top (required)>'

  2) Create Media Video object works with a video object with a valid role in contentMetadata
     Failure/Error: expect(Dir.children(File.join(object_staging_dir, 'content')).size).to eq 18
     
       expected: 18
            got: 27
     
       (compared using ==)
     # ./spec/features/preassembly_run/media_video_spec.rb:109:in `block (2 levels) in <top (required)>'
     # ./spec/features/preassembly_run/media_video_spec.rb:80:in `block (3 levels) in <top (required)>'
     # ./spec/features/preassembly_run/media_video_spec.rb:79:in `block (2 levels) in <top (required)>'

Finished in 1 minute 7.75 seconds (files took 23.49 seconds to load)
185 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/features/preassembly_run/media_audio_spec.rb:69 # Create Media Audio object is expected to eq 12
rspec ./spec/features/preassembly_run/media_video_spec.rb:84 # Create Media Video object works with a video object with a valid role in contentMetadata
```

**Comment by ndushay** [comment]
apparently I had some cruft in my test_data/media_xx_objects folders.  all better.
