### ISSUE TITLE
haml problems on Honeybadger Deploy Notification

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/pre-assembly#98]
using honeybadger the way it is, we get this deploy notification:
```
honeybadger:deploy
      Notifying Honeybadger of deploy.
      01 RAILS_ENV=production /usr/local/rvm/bin/rvm 2.4.4 do bundle exec honeybadger deploy --environment stage --revision e8c15c6847a739376aeeb9c34b5abf737…
      01 !! --- Honeybadger command failed --------------------------------------------- !!
      01
      01 # What did you try to do?
      01
      01   You tried to execute the following command:
      01   `honeybadger deploy --environment stage --revision e8c15c6847a739376aeeb9c34b5abf737280b772 --repository ssh://git@github.com/sul-dlss/pre-assembl…
      01
      01 # What actually happend?
      01
      01   We encountered a Ruby exception and were forced to cancel your request.
      01
      01 # Error details
      01
      01   NameError: uninitialized constant Haml::ActionView
      01     /opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/safe_erubis_template.rb:3:in `<module:Haml>'
      01     /opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/safe_erubis_template.rb:1:in `<top (required)>'
      01     /opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/railtie.rb:21:in `require'
      01     /opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/railtie.rb:21:in `<top (required)>'
      01     /opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml.rb:23:in `require'


```

**Comment by atz** [comment]
The deploy itself seems to succeed, but the notification to honeybadger crashes on an unexpected dependency issue.

**Comment by atz** [comment]
The chain of dependencies that gets us to `haml` is singular:
```
active-fedora (8.5.0) -> rdf-rdfxml (1.99.0) -> rdf-rdfa (1.99.1) -> haml (~> 4.0)
```
Our version of `haml` is `4.0.7`.

There are no later **minor** versions of anything in that chain that would allow us to upgrade easily.  So to get a newer `haml` likely involves breaking changes. 

The bigger question is why does this matter when initializing Honeybadger?

**Comment by ndushay** [comment]
It's possible that requiring the erubis gem will help ... but it seems to still bump into haml issues after that.

**Comment by ndushay** [comment]
See also https://github.com/samvera/hydra-head/commit/67d620ae4e8e8e72a3621f961e607fca9f55e84d. (require 'action_view' statement)

**Comment by atz** [comment]
Looks like @jcoyne already ran into this and prompted `rdf-rdfa` to accept a fix.  
https://github.com/ruby-rdf/rdf-rdfa/issues/23

The problem is that we are locked into too old of a version of that gem to benefit from it.
